Repository everfu/hexo-theme-solitude, pull requests merged in 2024-05, with the labels that each got.

#267 perf[Resubmission]: 类目栏以及部分样式
  languages/default.yml
  languages/en.yml
  languages/zh-CN.yml
  languages/zh-TW.yml
  layout/includes/widgets/home/categoryBar.pug
  source/css/_global/index.styl
  source/css/_layout/aside.styl
  source/css/_layout/other.styl
  source/css/_mode/index.styl
  source/css/_page/_about/reward.styl
  source/css/_page/_home/category-bar.styl
  source/css/_page/_home/home-top.styl
  source/css/_post/tools.styl
Labels: 已知问题

#286 feat: 公祭日呈现灰度色彩
  _config.yml
  layout/includes/inject/head.pug
  source/css/_global/index.styl
Labels: 新功能

#288 feat[about]: 新增百度统计数据
  layout/includes/widgets/page/about/other.pug
  source/css/_layout/footer.styl
  source/css/_layout/other.styl
  source/css/_page/_about/skills.styl
  source/css/_page/_about/statistic.styl
  source/css/_page/_home/home-top.styl
  source/css/_page/other.styl
Labels: 新功能

#290 feat[sayhello]: 获取用户昵称，选择相应的问候语
  languages/default.yml
  languages/en.yml
  languages/zh-CN.yml
  languages/zh-TW.yml
  layout/includes/head/config.pug
  source/js/main.js
Labels: 新功能

#292 feat✨
  _config.yml
  languages/default.yml
  languages/en.yml
  languages/zh-CN.yml
  languages/zh-TW.yml
  layout/includes/head/config.pug
  layout/includes/inject/head.pug
  layout/includes/page/says.pug
  layout/includes/widgets/page/about/other.pug
  package.json
  source/css/_global/index.styl
  source/css/_layout/footer.styl
  source/css/_layout/other.styl
  source/css/_page/_about/skills.styl
  source/css/_page/_about/statistic.styl
  source/css/_page/_home/home-top.styl
  source/css/_page/other.styl
  source/css/_page/says.styl
  source/js/main.js
Labels: 已知问题, 新功能

#293 feat✨
  layout/includes/inject/head.pug
  layout/includes/widgets/third-party/comments/artalk.pug
  layout/includes/widgets/third-party/news-comment/artalk.pug
  layout/post.pug
  package.json
  plugins.yml
  scripts/filter/default.js
  source/css/_layout/console.styl
  source/css/_layout/header.styl
  source/js/main.js
  source/js/third_party/efu_ai.min.js
Labels: 已知问题, 新功能
